{% set name = "OpenFBX" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/nem0/OpenFBX/archive/v{{ version }}.tar.gz
    sha256: d6495e05d469bf2c51b860bb0518db6fb2ccf1df9a542a6b1c0f618202641e94

build:
  number: 7
  run_exports:
    - {{ pin_subpackage('openfbx', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
  host:
    - libdeflate

test:
  commands:
    - test -f $PREFIX/share/openfbx/openfbxConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\share\\openfbx\\openfbxConfig.cmake exit 1  # [win]

about:
  home: https://github.com/nem0/OpenFBX
  summary: 'Lightweight open source FBX importer'
  description: |
    Lightweight open source FBX importer. Used in Lumix Engine and Flax Engine. It's an almost
    full-featured importer. It can load geometry (with uvs, normals, tangents, colors), skeletons,
    animations, blend shapes, materials, textures, cameras and lights.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/nem0/OpenFBX

extra:
  recipe-maintainers:
    - jeongseok-meta
